name: colorful_cmd
description: A library for building a beautiful command line application in dart.
version: 1.5.7
homepage: https://alanalbert.github.io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  console: ^3.1.0
  args: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
